settings:
  legacy:
    force: false
    interval: 0s

schema:
  - name: api-calendar
    path: cmd/api/calendar
    env:
      API_PORT: aaaa
      API_HTTP_COMPRESS: false
      LOGGER_VERBOSE: true
      LOGGER_PATH: ../../../log
    commands: 
      run: 
        status: true
        dir: cmd/api/calendar
    watcher:
      extensions:
      - go
      paths:
      - ../../../
      ignored_paths:
      - ../../../internal/api/queue
      - ../../../internal/consumer
      # Default paths to be ignored
      - ../../../.git
      - ../../../vendor
      - ../../../docs
      - ../../../dist

  - name: api-queue
    path: cmd/api/queue
    env:
      API_PORT: 8081
      API_HTTP_COMPRESS: false
      LOGGER_VERBOSE: true
      LOGGER_PATH: ../../../log
    commands:
      run:
        status: true
        dir: cmd/api/queue
    watcher:
      extensions:
      - go
      paths:
      - ../../../
      ignored_paths:
      - ../../../internal/api/calendar
      - ../../../internal/consumer
      # Default paths to be ignored
      - ../../../.git
      - ../../../vendor
      - ../../../docs
      - ../../../dist

  - name: consumer-queue
    path: cmd/consumer/queue
    commands: 
      run: 
        status: true
        dir: cmd/consumer/queue
    watcher:
      extensions:
      - go
      paths:
      - ../../../
      ignored_paths:
      - ../../../internal/api
      # Default paths to be ignored
      - ../../../.git
      - ../../../vendor
      - ../../../docs
      - ../../../dist
